# Generated by Django 2.1.1 on 2018-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180920_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='product_currency',
            field=models.CharField(default='грн', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_path',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
