# Generated by Django 2.1.1 on 2018-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180921_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
