# Generated by Django 2.1.1 on 2018-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180921_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
