# Generated by Django 2.1.1 on 2018-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
