# Generated by Django 2.1.1 on 2018-10-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180921_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStates',
            fields=[
                ('product_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_state_code', models.CharField(default=None, max_length=500)),
                ('product_state_name', models.CharField(default=None, max_length=500)),
                ('product_state_description', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'shop_product_states',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.ProductStates'),
        ),
    ]
