# Generated by Django 2.1.1 on 2018-10-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_producttocategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_name', models.CharField(default=None, max_length=500)),
                ('filter_description', models.CharField(default=None, max_length=500)),
                ('filter_code', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('filter_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_group_name', models.CharField(default=None, max_length=500)),
                ('filter_group_description', models.CharField(default=None, max_length=500)),
                ('filter_group_code', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop_filter_group',
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='filter_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FilterGroup'),
        ),
    ]
