# Generated by Django 2.1.1 on 2018-10-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181006_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductToFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Filter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'db_table': 'shop_product_to_filter',
            },
        ),
    ]
