# Generated by Django 2.1.1 on 2018-10-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_filtertocategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image_path',
            new_name='product_optional_image_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img_path',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_photo',
            field=models.ImageField(default=None, upload_to='product_photos'),
        ),
    ]
