# Generated by Django 2.1.1 on 2018-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20181018_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_optional_image_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
