# Generated by Django 2.1.1 on 2018-10-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20181018_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_image_order_no',
            field=models.IntegerField(default=1),
        ),
    ]
