# Generated by Django 2.1.1 on 2018-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20181018_1929')
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
