# Generated by Django 2.1.1 on 2018-11-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_category_category_sector'),
        ('shop', '0016_productimage_product_image_order_no'),
    ]

    operations = [
    ]
