# Generated by Django 2.1.1 on 2018-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20181113_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
