# Generated by Django 2.1.1 on 2018-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20181113_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
