# Generated by Django 2.1.1 on 2018-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_seo',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
