# Generated by Django 2.1.1 on 2018-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_product_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(default=None, max_length=100)),
                ('setting_code', models.CharField(default=None, max_length=100)),
                ('setting_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
