# Generated by Django 2.1.1 on 2018-11-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20181114_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='setting_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
