# Generated by Django 2.1.1 on 2018-11-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20181115_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtertocategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filtertocategory',
            name='filter',
        ),
        migrations.DeleteModel(
            name='FilterToCategory',
        ),
    ]
