# Generated by Django 2.1.1 on 2018-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20181117_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('carousel_id', models.AutoField(primary_key=True, serialize=False)),
                ('carousel_name', models.CharField(max_length=500)),
                ('carousel_photo', models.ImageField(default=None, upload_to='carousel_photos')),
                ('carousel_image_order_no', models.IntegerField(default=1)),
                ('carousel_link', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shop_carousel_photo',
            },
        ),
    ]
