# Generated by Django 2.1.1 on 2018-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
