# Generated by Django 2.1.1 on 2018-12-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_carousel_carousel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_photos'),
        ),
    ]
